# Generated by Django 3.1.5 on 2021-01-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_newuser_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='catalog',
        ),
        migrations.AddField(
            model_name='newuser',
            name='catalog',
            field=models.CharField(default='catalog', max_length=50),
        ),
    ]
