# Generated by Django 3.1.5 on 2021-01-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('user', '0004_auto_20210126_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='catalog',
        ),
        migrations.AddField(
            model_name='newuser',
            name='catalog',
            field=models.ManyToManyField(blank=True, to='main.Product'),
        ),
    ]
